language: c++
os: linux
dist: bionic

compiler:
  - gcc
  - clang
install:
  - sudo apt install libcurl4 libcurl4-openssl-dev

script:
  - cmake --version
  - mkdir build
  - cd build
  - cmake ..
  - make