name: Ubuntu

on:
    push:
        - master
    pull_request:

jobs:
    build-ubuntu:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v2

            - name: install libs
              run: sudo apt update; sudo apt install libcurl4 libcurl4-openssl-dev

            - name: cmake
              run: mkdir build; cd build; cmake ..; cmake --build .
                

